### ISSUE TITLE
Dask is causing tests to fail

### ISSUE THREAD

**Issue by wigging** [ORNL/flowcept#168]
Dask appears to be causing tests to fail in the run-tests-kafka and run-tests workflows. Most of the errors seem to be related to the following:

```text
packages/flowcept/flowceptor/adapters/dask/dask_interceptor.py", line 50, in get_run_spec_data
    func = run_spec[0]
TypeError: 'Task' object is not subscriptable
```

**Comment by renan-souza** [comment]
Dask has been releasing new versions frequently these past days. I'm even more suspicious that something changed in their API. But I still need to investigate it further.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/9145bd5e-3b7b-466d-96e6-590a2f8bdccc">
https://pypi.org/project/distributed/#history as of Nov 14th 2024

This raises discussion for another issue. For errors like those I was specifying the versions for the dependencies on those old requirements.txt files that were guaranteed to work. Now we removed the versions from most of these dependencies, opening room for these unpredictable errors.

There are pros and cons for keeping the dependencies' version so flexible. I would love to keep FlowCept's dependencies as flexible as possible and it would be great if FlowCept always worked fine with the latest versions of its dependencies, but since FlowCept relies on third parties' APIs to access their data, which are subject to change, we might need to think of a different solution.

There is one open issue related to this https://github.com/ORNL/flowcept/issues/106
and since it is a recurring problem, I even created a label for this. If we think of a good solution, this might solve a major pain in this project.

**Comment by wigging** [comment]
That's a lot of releases for Dask in a short amount of time. Hopefully they mention API changes or other breaking changes in the changelog. Did you see anything in the changelog that might be causing the errors?

As you mention, there are pros and cons for fixing the version numbers for the dependencies. I don't like to pin version numbers because it just delays the inevitable task to support the latest package version. I prefer to restrict the Python version and let the package manager (pip, conda, etc) handle the dependencies and versions. Pinning the version may fix the immediate issue but in the long run it will actually cause more problems. Lock files are supposed to make this stuff easier to deal with but I always have problems with keeping the lock file in sync.

**Comment by renan-souza** [comment]
As this issue is only specific to Dask, let's move this discussion to the issue https://github.com/ORNL/flowcept/issues/106.

**Comment by renan-souza** [comment]
@wigging The dask errors were gone with your latest commit https://github.com/ORNL/flowcept/commit/659cf69ded19d19b26852487fff7e5211535ced8

But since the dask version is now fixed, do you recommend to close this issue or keep it open to try to make Flowcept work with the latest version of Dask (once Dask estabilizes)?

**Comment by wigging** [comment]
Closing this because pinning the Dask version to 2024.10.0 fixes the original issue. A better solution needs to be investigated so the package isn't stuck on an old version of Dask. But this will do for now.
